### ISSUE TITLE
Location Acesss from Privacy Dashboard pops up every thirty seconds

### ISSUE THREAD

**Issue by xFaultx** [ProtonAOSP/android_manifest#12]
I am getting nonstop location polling requests that keep causing that annoying green popup in the top right corner. I've verified with my wife who has Android 12 but not proton, and no where near as many popups. I mean it's roughly every 20 seconds. These are for apps like maps, play services, and a widget that have always access for seeing my location, which as far as I understand Android should not show the popup for. Any help?

**Comment by kdrag0n** [comment]
The location indicator has been configurable since v12.3.0.
