### ISSUE TITLE
community other then telegram

### ISSUE THREAD

**Issue by nutpantz** [ProtonAOSP/android_manifest#24]
Not everyone wants to have to sign up to telegram just to read about proton aosp. 
Many many people want a custom ROM to avoid google and their services and don't want to give telegram a phone number or use their app to be part of the community.

**Comment by parcelcat** [comment]
Yes, the telephone number requirement is going to deter some privacy-conscious users. [Matrix](https://matrix.org/) ([Element](https://element.io/)) would be better.

**Comment by kdrag0n** [comment]
There are no plans to expand to any other platforms at the moment.
