### ISSUE TITLE
[raven] 12.4.1 fails to build: Rust dependency error on DnsResolver

### ISSUE THREAD

**Issue by AnonymousProxy987** [ProtonAOSP/android_manifest#30]
A clean build of ProtonAOSP 12.4.1 for Pixel 6 Pro (raven) is failing with this error:

```
[ 99% 247/249] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"     --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
error: packages/modules/DnsResolver/Android.bp:377:1: "libdoh_ffi_for_test" depends on undefined module "libbase64_rust"
04:03:02 soong bootstrap failed with: exit status 1

#### failed to build some targets (42 seconds) ####
```

It looks like [ProtonAOSP's DnsResolver module](https://github.com/ProtonAOSP/android_packages_modules_DnsResolver) now includes some Rust build components as of this update. Additionally, [proton.xml](https://github.com/ProtonAOSP/android_manifest/commit/f2c0040cff25ded1ca51b5bc655ae6945a71bb01) was recently updated to also include some Rust crates. However, it seems like the [base64 crate](https://cs.android.com/android/platform/superproject/+/master:external/rust/crates/base64/Android.bp?q=libbase64_rust) may not have been added? Based on the above error, it seems like it's the one that is missing.

**Comment by jgudec** [comment]
Merely chipping in to confirm the same issue while building (a GSI, if that matters).
