### ISSUE TITLE
More devices? Pixel 3a...

### ISSUE THREAD

**Issue by lbdroid** [ProtonAOSP/android_manifest#4]
I would love to see this available for the 3a. Nice device, but there are not a lot of options for it.

**Comment by kdrag0n** [comment]
I don't own a Pixel 3a (nor do I want one) and no one with high-quality device trees has stepped up to maintain it, so unfortunately, this is unlikely to happen any time soon.

**Comment by julianfairfax** [comment]
If I or someone else were able to build it and confirm that everything works, would you maintain it then? If not, could I or someone else maintain it in accordance with whatever rules and release schedule this project has in place?

**Comment by kdrag0n** [comment]
Feel free to maintain unofficial builds, as long as they're clearly marked as such. We don't have infrastructure to adopt more official devices at the moment.

**Comment by lbdroid** [comment]
> If I or someone else were able to build it and confirm that everything works, would you maintain it then? If not, could I or someone else maintain it in accordance with whatever rules and release schedule this project has in place?

@julianfairfax ;
GrapheneOS supports Pixel 3a. That's probably a good place for you to head to, since it offers substantially improved security.
