### ISSUE TITLE
Phone call hangs up byitself on pixel 5

### ISSUE THREAD

**Issue by Bf2multi100** [ProtonAOSP/android_manifest#5]
Having a weird issue with my pixel 5.

When i am on a call with the gapps installed.

If i lock my phone (or screen turns off automatically), the phone call hangs up by itself without me doing anything.

Using verizon on my pixel 5. 

Any ideas?

**Comment by kdrag0n** [comment]
No one else has reported any issues like this and it's been a while since this was reported, so I'm closing it as something that is most likely no longer an issue. Feel free to open a new issue if it persists.
