### ISSUE TITLE
New "SIMon mobile" operator doesn't have proper carrier id?

### ISSUE THREAD

**Issue by ralfbergs** [ProtonAOSP/android_manifest#6]
Hi guys.

It seems that the pretty new (launched in June/July?) German operator "[->SIMon mobile](https://www.simonmobile.de/)" doesn't have a carrier id defined in ProtonAOSP for the Pixel 2. It just shows up as "Welcome" (actually it is "Willkommen", because the phone is switched to "German").

Is my interpretation why the carrier id doesn't show up properly correct? The phone previous had a SIM from "LIDL-Connect," and that did show up properly on the phone. Both brands are operated "in the back" by Vodafone, so I'm pretty sure they know what they are doing, and the SIM has been properly manufactured, so it must be the phone methinks?

Can I somehow help shedding some light on this? I'm pretty technical, "adb" and command-line is easy for me, so please let me know what I can do to investigate...

Many thanks in advance for looking into this.

Kind regards,

Ralf

**Comment by kdrag0n** [comment]
Carrier names are provided by Google's CarrierSettings service, which stores carrier info in a binary format in /product/etc/CarrierSettings. Google will probably add settings for the carrier in due time, but as the Pixel 2 is no longer receiving updates from either ProtonAOSP or Google, I'm afraid this issue won't be fixed. I'm not aware of any way to change the carrier name manually.

**Comment by ralfbergs** [comment]
@kdrag0n thanks for your response, Danny.

To make it crystal clear: You're saying you won't release a more recent build for the Pixel 2? Or did I get you wrong here?

**Comment by kdrag0n** [comment]
Correct. As per the announcement on Telegram:

> **ProtonAOSP is no longer supporting the Pixel 2 series officially.**
>
> Anyone is welcome to build unofficial updates for the Pixel 2 series, but as we have updated to Android 12 and the Pixel 2 has reached end-of-life, device support will have to be ported and updated unofficially. Unfortunately, we don't have the time or resources to do so, and we are more interested in focusing on actively-supported devices.
>
> We also lack resources and interest in continuing Android 11-based security updates, which are losing value as security vulnerabilities in proprietary code can no longer be fixed.
>
> ProtonAOSP is [actively supporting](https://protonaosp.kdrag0n.dev/getting-started/supported-devices) the Pixel 4, 4 XL, 5, and 4a 5G with builds based on Android 12, but the Pixel 2 and 2 XL will no longer receive updates. **Thank you for using ProtonAOSP while it lasted!**

**Comment by ralfbergs** [comment]
Thanks for clarifying, Danny.

That's really a pity. Migrating to 12 would make a lot of sense, but unfortunately as you mentioned that will also not be supported for anything below a Pixel 4.

I would love to create unofficial builds, but I simply lack the spare time and experience to do so.

Thanks for supporting it until recently!
